# SPDX-License-Identifier: Apache-2.0
"""Pinned ccache launcher for the CMake-driven CUDA build actions.

ccache lives in Ubuntu universe, which this workspace deliberately does not
index: the universe and updates suites made `rules_distroless` resolution fail
on transient snapshot outages. The three debs are pinned directly against the
immutable snapshot instead, so the launcher is content-addressed and enters the
CAS exactly once. `libxxhash0`, `libzstd1`, and `libstdc++6` already ship in
the worker image.
"""

_SNAPSHOT = "https://snapshot.ubuntu.com/ubuntu/20260901T000000Z/pool"

_DEBS = {
    "arm64": [
    {
        "path": "universe/c/ccache/ccache_4.13.6-1_arm64.deb",
        "sha256": "eadd6e34d6fd22becf955cf3b119496ac86614263ef5a120c6544fe192f957f4",
    },
    {
        "path": "universe/f/fmtlib/libfmt10_10.1.1+ds1-4build1_arm64.deb",
        "sha256": "c73742de8c9ed20d7c611a883b6476f5ed09cc9790ab1a38e96e0f90a4fe4cce",
    },
    {
        "path": "universe/h/hiredis/libhiredis1.1.0_1.2.0-6ubuntu5_arm64.deb",
        "sha256": "1910431a9f30ecfb4835e747567305daff1f9cdece2216eadfae4ff6931be1ed",
    },
    ],
    "x86_64": [
        {
            "path": "universe/c/ccache/ccache_4.13.6-1_amd64.deb",
            "sha256": "405e70840b9cb560fd3844fc1b980784684511b8c7baba374e28e65189895357",
        },
        {
            "path": "universe/f/fmtlib/libfmt10_10.1.1+ds1-4build1_amd64.deb",
            "sha256": "656ab858fbd4424d4a09097ffc6f8102828298d430a1e3c9f13eaa857b93bc95",
        },
        {
            "path": "universe/h/hiredis/libhiredis1.1.0_1.2.0-6ubuntu5_amd64.deb",
            "sha256": "117b337534114ed5447c8618fc19440b929dbb2cf7fac7de6d6b7b1ddd4206bf",
        },
    ],
}

def _ccache_repository_impl(ctx):
    for index, deb in enumerate(_DEBS[ctx.attr.cpu]):
        deb_path = "debs/%d.deb" % index
        ctx.download(
            url = "%s/%s" % (_SNAPSHOT, deb["path"]),
            output = deb_path,
            sha256 = deb["sha256"],
        )
        result = ctx.execute([
            "ar",
            "x",
            "--output",
            "debs",
            deb_path,
            "data.tar.zst",
        ])
        if result.return_code:
            fail("extracting %s failed: %s" % (deb_path, result.stderr))
        ctx.extract("debs/data.tar.zst", output = "root")

    if not ctx.path("root/usr/bin/ccache").exists:
        fail("ccache package did not provide root/usr/bin/ccache")

    # Actions extract one tar rather than discovering a package layout, matching
    # how the CUDA redistributables are staged.
    result = ctx.execute([
        "tar",
        "--sort=name",
        "--mtime=@0",
        "--owner=0",
        "--group=0",
        "--numeric-owner",
        "-C",
        "root",
        "-cf",
        "ccache.tar",
        "usr",
    ])
    if result.return_code != 0:
        fail("assembling ccache.tar failed: %s" % result.stderr)

    ctx.file("BUILD.bazel", """# Generated by ccache.bzl.
exports_files(["ccache.tar"], visibility = ["//visibility:public"])
""")

_ccache_repository = repository_rule(
    implementation = _ccache_repository_impl,
    attrs = {"cpu": attr.string(values = ["arm64", "x86_64"], mandatory = True)},
)

def _ccache_extension_impl(_ctx):
    _ccache_repository(name = "ccache", cpu = "arm64")
    _ccache_repository(name = "ccache_x86_64", cpu = "x86_64")

ccache = module_extension(implementation = _ccache_extension_impl)
