# SPDX-License-Identifier: Apache-2.0
"""Hermetic CUDA toolkit repository assembled from NVIDIA redistributables."""

_CUDA_COMPONENTS = [
    "cccl",
    "cuda_crt",
    "cuda_cupti",
    "cuda_cudart",
    "cuda_culibos",
    "cuda_nvcc",
    "cuda_nvml_dev",
    "cuda_nvrtc",
    "cuda_profiler_api",
    "cuda_tileiras",
    "libnvvm",
    "libcublas",
    "libcufft",
    "libcurand",
    "libcusolver",
    "libcusparse",
    "libnvjitlink",
    "libnvjpeg",
]

_CUDA_AUXILIARY_ARCHIVES = [
    {
        "url": "https://developer.download.nvidia.com/compute/cudnn/redist/cudnn/linux-sbsa/cudnn-linux-sbsa-9.24.0.43_cuda13-archive.tar.xz",
        "sha256": "f9b71a8a070073f20224746d9216ac4e28de7f59b54a8c47200ff506e6d4d830",
    },
    {
        "url": "https://developer.download.nvidia.com/compute/cusparselt/redist/libcusparse_lt/linux-aarch64/libcusparse_lt-linux-aarch64-0.8.1.1_cuda13-archive.tar.xz",
        "sha256": "0fcf5808f66c71f755b4a73af2e955292e4334fec6a851eea1ac2e20878602b7",
    },
]


def _cuda_repository_impl(ctx):
    manifest = json.decode(ctx.read(ctx.attr.manifest))
    for component in _CUDA_COMPONENTS:
        entry = manifest[component]["linux-sbsa"]
        ctx.download_and_extract(
            url = "https://developer.download.nvidia.com/compute/cuda/redist/%s" % entry["relative_path"],
            output = "components/%s" % component,
            sha256 = entry["sha256"],
        )

    for index, archive in enumerate(_CUDA_AUXILIARY_ARCHIVES):
        ctx.download_and_extract(
            url = archive["url"],
            output = "components/aux_%d" % index,
            sha256 = archive["sha256"],
        )

    # NVIDIA archives share a CUDA prefix. Starlark disallows recursive helper
    # calls, so merge each tree with direct argv-form cp rather than a shell.
    ctx.file("toolkit/.keep", "")
    for archive in ctx.path("components").readdir():
        children = archive.readdir()
        if len(children) != 1 or not children[0].is_dir:
            fail("expected one root directory in %s" % archive)
        result = ctx.execute(["cp", "-a", str(children[0].realpath) + "/.", "toolkit"])
        if result.return_code:
            fail("failed to merge %s: %s" % (archive, result.stderr))

    result = ctx.execute([
        "tar",
        "--dereference",
        "--sort=name",
        "--mtime=@0",
        "--owner=0",
        "--group=0",
        "--numeric-owner",
        "--exclude=.keep",
        "-C",
        "toolkit",
        "-cf",
        "toolkit.tar",
        ".",
    ])
    if result.return_code:
        fail("failed to archive CUDA toolkit: %s" % result.stderr)

    _write_cusparselt_tar(ctx)
    ctx.file("BUILD.bazel", """# Generated by cuda_redist.bzl.
exports_files(["toolkit.tar", "cusparselt.tar"], visibility = ["//visibility:public"])
""")

def _write_cusparselt_tar(ctx):
    archive_root = ctx.path("components/aux_1").readdir()
    if len(archive_root) != 1 or not archive_root[0].is_dir:
        fail("expected one root directory in components/aux_1")

    source = archive_root[0].get_child("lib")
    if not source.is_dir:
        fail("expected lib directory in cuSPARSELt archive")

    # The CUDA base image publishes /usr/local/cuda as a symlink to the
    # versioned toolkit. A layer carrying that path as a real directory
    # replaces the symlink and hides the whole CUDA runtime, so keep this
    # library on its own path and export it through LD_LIBRARY_PATH.
    destination = "cusparselt/opt/cusparselt/lib"
    ctx.file("%s/.keep" % destination, "")
    libraries = [
        entry
        for entry in source.readdir()
        if not entry.is_dir and entry.basename.startswith("libcusparseLt.so")
    ]
    if not libraries:
        fail("cuSPARSELt archive contains no libcusparseLt.so libraries")
    for library in libraries:
        ctx.symlink(library, "%s/%s" % (destination, library.basename))

    result = ctx.execute([
        "tar",
        "--dereference",
        "--sort=name",
        "--mtime=@0",
        "--owner=0",
        "--group=0",
        "--numeric-owner",
        "--exclude=.keep",
        "-C",
        "cusparselt",
        "-cf",
        "cusparselt.tar",
        "opt",
    ])
    if result.return_code:
        fail("failed to archive cuSPARSELt runtime: %s" % result.stderr)

_cuda_repository = repository_rule(
    implementation = _cuda_repository_impl,
    attrs = {"manifest": attr.label(allow_single_file = True, mandatory = True)},
)


def _cuda_redist_impl(ctx):
    _cuda_repository(
        name = "cuda_sbsa",
        manifest = Label("//cuda:redistrib_13.3.1.json"),
    )

cuda_redist = module_extension(implementation = _cuda_redist_impl)
