# SPDX-License-Identifier: Apache-2.0
"""Profile-driven, commit-pinned source archives."""

# Bazel's default ctx.execute timeout is 600 seconds. PyTorch's recursive
# submodule tree and the vendored Cargo registry both exceed that on a cold
# checkout, and the failure surfaces as an opaque "Timed out" during analysis.
_NETWORK_TIMEOUT = 3600

# Archiving multi-gigabyte checkouts also runs past the default.
_ARCHIVE_TIMEOUT = 1800

def _source_build(cargo_vendor):
    files = ["source.tar", "source.identity.json"]
    if cargo_vendor:
        files.append("cargo-vendor.tar")
    return """# Generated by sources.bzl.
exports_files(
    %s,
    visibility = ["//visibility:public"],
)
""" % repr(files)

def _pinned_source_repository_impl(ctx):
    source = ctx.path("src")
    patches = []
    # Fetch the locked object into an empty repository instead of cloning the
    # remote. A full clone of PyTorch transfers its entire history for one
    # pinned commit, which is what exhausted the fetch timeout in CI and which
    # GitHub's HTTP/2 endpoint resets outright on a slower link. A depth-1
    # fetch of the exact commit also works for a pin outside the advertised
    # default branch's history.
    for command, message in (
        (["git", "init", "--quiet", source], "git init failed for %s"),
        (["git", "-C", source, "remote", "add", "origin", ctx.attr.remote], "git remote add failed for %s"),
    ):
        result = ctx.execute(command)
        if result.return_code:
            fail((message + ": %s") % (ctx.attr.remote, result.stderr))

    result = ctx.execute(
        ["git", "-C", source, "fetch", "--depth=1", "origin", ctx.attr.commit],
        timeout = _NETWORK_TIMEOUT,
    )
    if result.return_code:
        fail("git fetch failed for %s: %s" % (ctx.attr.commit, result.stderr))

    result = ctx.execute(["git", "-C", source, "checkout", "--detach", ctx.attr.commit])
    if result.return_code:
        fail("git checkout failed for %s: %s" % (ctx.attr.commit, result.stderr))

    if ctx.attr.recursive_init_submodules:
        result = ctx.execute(
            ["git", "-C", source, "submodule", "update", "--init", "--recursive", "--jobs=8"],
            timeout = _NETWORK_TIMEOUT,
        )
        if result.return_code:
            fail("git submodule update failed for %s: %s" % (ctx.attr.remote, result.stderr))

    for patch in ctx.attr.patches:
        patch_path = ctx.path(patch)
        # External commands do not register file reads with Bazel.
        ctx.watch(patch_path)
        result = ctx.execute(["sha256sum", patch_path])
        if result.return_code:
            fail("hashing %s failed: %s" % (patch, result.stderr))
        patches.append({
            "label": str(patch),
            "sha256": result.stdout.split(" ")[0],
        })
        result = ctx.execute(["patch", "-d", source, "-p1", "-i", patch_path])
        if result.return_code:
            fail("applying %s failed: %s" % (patch, result.stderr))

    # Preserve source symlinks instead of dereferencing them. PyTorch's ittapi
    # checkout contains a cyclic link which Bazel's recursive glob cannot read.
    result = ctx.execute([
        "tar",
        "-C",
        source,
        "--exclude=.git",
        "--sort=name",
        "--mtime=@0",
        "--owner=0",
        "--group=0",
        "--numeric-owner",
        "-cf",
        "source.tar",
        ".",
    ], timeout = _ARCHIVE_TIMEOUT)
    if result.return_code:
        fail("source archive failed for %s: %s" % (ctx.attr.remote, result.stderr))
    ctx.file("source.identity.json", json.encode({
        "commit": ctx.attr.commit,
        "patches": patches,
        "remote": ctx.attr.remote,
    }) + "\n")
    if ctx.attr.cargo_vendor:
        manifest = source
        for component in ctx.attr.cargo_manifest.split("/"):
            manifest = manifest.get_child(component)
        vendor = ctx.path("cargo-vendor")
        result = ctx.execute([
            "cargo",
            "vendor",
            "--locked",
            "--manifest-path",
            manifest,
            vendor.get_child("vendor"),
        ], timeout = _NETWORK_TIMEOUT)
        if result.return_code:
            fail("cargo vendor failed for %s: %s" % (ctx.attr.remote, result.stderr))
        # Keep Cargo's source replacement relative to the action-local CARGO_HOME.
        config = result.stdout.replace(
            'directory = "%s"' % vendor.get_child("vendor"),
            'directory = "vendor"',
        )
        ctx.file("cargo-vendor/config.toml", config)
        result = ctx.execute([
            "tar",
            "-C",
            vendor,
            "--sort=name",
            "--mtime=@0",
            "--owner=0",
            "--group=0",
            "--numeric-owner",
            "-cf",
            "cargo-vendor.tar",
            ".",
        ], timeout = _ARCHIVE_TIMEOUT)
        if result.return_code:
            fail("cargo vendor archive failed for %s: %s" % (ctx.attr.remote, result.stderr))
    ctx.file("BUILD.bazel", _source_build(ctx.attr.cargo_vendor))

_pinned_source_repository = repository_rule(
    implementation = _pinned_source_repository_impl,
    attrs = {
        "remote": attr.string(mandatory = True),
        "commit": attr.string(mandatory = True),
        "recursive_init_submodules": attr.bool(default = False),
        "patches": attr.label_list(allow_files = True),
        "cargo_vendor": attr.bool(default = False),
        "cargo_manifest": attr.string(default = "rust/Cargo.toml"),
    },
)


def _sources_impl(ctx):
    for mod in ctx.modules:
        for tag in mod.tags.profile:
            profile = json.decode(ctx.read(tag.manifest))
            prefix = profile["name"].replace("-", "_")
            for name, source in profile["sources"].items():
                _pinned_source_repository(
                    name = "%s_%s" % (prefix, name),
                    remote = source["remote"],
                    commit = source["commit"],
                    recursive_init_submodules = source.get("recursive_init_submodules", False),
                    patches = tag.vllm_patches if name == "vllm" else [],
                    cargo_vendor = source.get("cargo_vendor", False),
                    cargo_manifest = source.get("cargo_manifest", "rust/Cargo.toml"),
                )

profile_sources = module_extension(
    implementation = _sources_impl,
    tag_classes = {
        "profile": tag_class(attrs = {
            "manifest": attr.label(mandatory = True, allow_single_file = True),
            "vllm_patches": attr.label_list(allow_files = True),
        }),
    },
)
