# SPDX-License-Identifier: Apache-2.0
# Generated by scripts/vllmb12x-included-changes.py. Do not edit by hand.
"""Registry description for the image this profile builds."""

VLLM_IMAGE_DESCRIPTION = "vLLM 588bc2641de6 + B12X ca8e62faa41b for NVIDIA Blackwell SM12x GPUs, carrying local-inference-lab/vllm#777 #798 #800 #801 #802 #803 #805 #806 #807 #809 #810 #812 #813. Linux ARM64 and AMD64, CUDA 13.4.1, Python 3.12. Full change ledger in the README below."
