# SPDX-License-Identifier: Apache-2.0
# Generated by scripts/vllmb12x-included-changes.py. Do not edit by hand.
"""Registry description for the image this profile builds."""

VLLM_IMAGE_DESCRIPTION = "vLLM a307c6ffaf96 + B12X b7f8879a4ded for NVIDIA Blackwell SM12x GPUs, carrying local-inference-lab/vllm#800. Linux ARM64 and AMD64, CUDA 13.4.1, Python 3.12. Full change ledger in the README below."
