# SPDX-License-Identifier: Apache-2.0
# Generated by scripts/vllmb12x-included-changes.py. Do not edit by hand.
"""Registry description for the image this profile builds."""

VLLM_IMAGE_DESCRIPTION = "vLLM ed6f2c5853c9 + B12X a83336581a3a for NVIDIA DGX Spark (GB10, sm_121a), carrying vllm-project/vllm#52917. Linux ARM64, CUDA 13.3.1, Python 3.12. Full change ledger in the README below."
