# SPDX-License-Identifier: Apache-2.0
# Generated by scripts/refresh-vllmb12x.py. Do not edit by hand.
"""PEP 440 distribution version for the vLLM wheel this profile builds.

Composed from the upstream vLLM base version declared in profile.json, the
local-inference-lab cycle that VLLM_SOURCE_REF names, and the first twelve
hexadecimal digits of the digest over the locked source set. The digest is a
pure function of the manifest, so identical inputs rebuild the same version;
recompute it with `scripts/refresh-vllmb12x.py --dry-run`.
"""

VLLM_BUILD_VERSION = "0.29.0+karmic.kraken.24cddfd39ccf"
VLLM_SOURCE_REF = "refs/heads/cycle/karmic-kraken"
VLLM_SOURCE_REVISION = "79efdd6695839d6a14791f2dd4b6340e31f31a02"
