# SPDX-License-Identifier: Apache-2.0
# Generated by scripts/refresh-vllmb12x.py. Do not edit by hand.
"""PEP 440 distribution version for the vLLM wheel this profile builds."""

VLLM_BUILD_VERSION = "0.1.dev1+vllmb12x.gab03e87100ef"
VLLM_SOURCE_REF = "refs/heads/dev/jovian-judgement"
VLLM_SOURCE_REVISION = "ab03e87100efa9536ec87e01994828b459c956ff"
